"""
deterministic_validators.py

FIXED AFTER REAL-MODEL CANARY RUNS 35482706294 / 35485028854 (v2 was never
run against a real model before that; this version incorporates the real
failure modes those two runs actually exhibited):

  STRUCTURAL FIX (review point 1): Stage 2 is now TWO separate contracts,
  not one:
    validate_stage2_decision_output()   -- decision, evidence_quality,
        theses, evidence-id roles, system_limitations. NEVER asks for or
        accepts entry/failure_exit fields at all.
    validate_stage2_actionability_output() -- entry/failure_exit ONLY,
        called only when the decision is CANDIDATE/HIGH_CONVICTION, with
        an enum that EXCLUDES NOT_ACTIONABLE/UNAVAILABLE entirely, so the
        model cannot reproduce the reported failure (decision=CANDIDATE +
        entry.status=NOT_ACTIONABLE + null prices) even in principle --
        that combination requires two different calls to both go wrong in
        two different, structurally incompatible ways, not one call
        picking an internally-contradictory combination from one shared
        enum space. For REJECT/WATCH, entry/failure_exit is no longer
        asked of the model at all -- it is deterministically assembled by
        assemble_final_stage2() in safe_finalizer.py, because it is
        always exactly the same fixed value regardless of the case; that
        is a structural fact, not a judgment call, so there is nothing
        for the model to get wrong.

  ALIAS FIX (review point 2): _text_mentions_family() previously matched
  on ANY individual word (>=3 chars) split out of a family_id, so generic
  words like "structure", "flow", "price", "information" caused massive
  false positives (e.g. "reasonable valuation" was detected as mentioning
  institutional_flow, mops_material_information, price_volume_structure,
  AND revenue, none of which the text was actually about). Replaced with
  FAMILY_ALIASES: a curated, per-family phrase list. A family is only
  considered "mentioned" if one of its own specific alias phrases appears
  verbatim as a substring -- generic single words are never aliases by
  themselves.

  VALUATION RULE UNIFIED (review point 3): Stage 1's prompt previously
  allowed SUPPORTIVE/CONTRADICTORY from "absolute valuation extreme" even
  without benchmark_available, while Stage 2's validator banned any
  cheap/expensive/reasonable claim without a benchmark -- directly
  contradictory instructions. Resolved in favor of the stricter,
  consistent rule: valuation with benchmark_available=False MUST be
  direction=NOT_INTERPRETABLE. This is now a HARD ERROR in Stage 1
  validation, not just a Stage 2 text-pattern check. (Stage 1's prompt
  file has been updated to match -- see stage1_extractor_prompt.py.)

  EVIDENCE-ROLE RULES TIGHTENED (review point 4): in addition to the
  existing SUPPORTIVE/MIXED-only and CONTRADICTORY/MIXED-only membership
  checks, added: (a) an explicit, clearly-worded rejection whenever a
  NEUTRAL or NOT_INTERPRETABLE family appears in ANY of primary/
  secondary/counter_evidence_ids (previously true only as an algebraic
  consequence of the membership checks, now also a named, specific error
  message); (b) every family with direction=CONTRADICTORY (strict, not
  MIXED) MUST appear in counter_evidence_ids -- it is no longer optional
  for the model to omit a contradictory family from counter_evidence.

  STRUCTURED REPAIR REQUESTS (review point 5): errors_to_repair_request()
  converts the existing human-readable error strings into a compact list
  of {field, problem, received, allowed} dicts wherever the error matches
  a known, enumerable pattern (which covers the vast majority of this
  module's error messages, since they are all generated by this same
  module in fixed formats). retry_orchestrator.py now sends this
  structured list to the model on retry, in addition to (not instead of)
  the raw error strings.
"""

from __future__ import annotations

import re
from typing import Any

from evidence_capability import derive_case_evidence_sets

# ---------------------------------------------------------------------------
# Shared enums
# ---------------------------------------------------------------------------

DIRECTION_VALUES = {"SUPPORTIVE", "CONTRADICTORY", "NEUTRAL", "MIXED", "NOT_INTERPRETABLE"}
TIMELINESS_VALUES = {"CURRENT", "STALE", "UNKNOWN_AGE"}
RELEVANCE_VALUES = {"HIGH", "MEDIUM", "LOW"}

DECISION_VALUES = {"REJECT", "WATCH", "CANDIDATE", "HIGH_CONVICTION"}
EVIDENCE_QUALITY_VALUES = {"STRONG", "MODERATE", "WEAK"}

# Actionability sub-contract enums deliberately EXCLUDE the non-actionable
# values (NOT_ACTIONABLE / UNAVAILABLE) -- this call is only ever made for
# CANDIDATE/HIGH_CONVICTION, so those values are not offered as an option.
ENTRY_STATUS_ACTIONABLE_VALUES = {"NOW", "WAIT_FOR_PULLBACK", "WAIT_FOR_CONFIRMATION"}
FAILURE_TRIGGER_ACTIONABLE_VALUES = {
    "PRICE_STRUCTURE_BREAK", "THESIS_INVALIDATION", "CATALYST_FAILURE",
    "VALUATION_EXPECTATION_BREAK", "MULTI_EVIDENCE_FAILURE",
}
NON_ACTIONABLE_DECISIONS = {"REJECT", "WATCH"}
ACTIONABLE_DECISIONS = {"CANDIDATE", "HIGH_CONVICTION"}

CRITIC_VERDICT_VALUES = {"APPROVE", "REVISE"}
CRITIC_PROBLEM_TYPES = {
    "UNGROUNDED_CLAIM", "CONTRADICTS_EXACT_OBSERVATIONS", "OVERSTATES_DIRECTION",
    "BENCHMARK_MISSING_BUT_VALUE_JUDGMENT_MADE", "SINGLE_PERIOD_TREATED_AS_TREND",
    "ROUTINE_FILING_TREATED_AS_CATALYST", "MIXED_EVIDENCE_TREATED_AS_UNIFORM",
    "CLAIM_NOT_REFLECTED_IN_EVIDENCE_ID_LISTS", "DECISION_INCONSISTENT_WITH_EVIDENCE_BALANCE",
    "ACTIONABILITY_PRICE_NOT_GROUNDED",
}
CRITIC_PROBLEM_REQUIRED_KEYS = {"field", "claim_text", "cited_evidence_id", "problem_type", "explanation"}
CRITIC_PROBLEM_FIELD_VALUES = {
    "bull_thesis", "bear_thesis", "decision_reason", "invalidation", "hypothesis",
    "evidence_quality", "decision", "entry_or_failure_exit",
}

VALUE_JUDGMENT_PHRASES = {
    "cheap", "expensive", "undervalued", "overvalued", "reasonable",
    "fairly valued", "attractively valued", "reasonable valuation",
    "便宜", "昂貴", "低估", "高估", "合理", "估值合理", "估值便宜", "估值偏低", "估值偏高",
}
DURATIVE_TREND_PHRASES = {
    "sustained growth", "continued growth", "ongoing growth", "continuation of growth",
    "trend of growth", "consistent growth",
    "持續成長", "持續增長", "延續成長", "穩定成長", "持續性成長",
}
CATALYST_PHRASES = {
    "catalyst", "positive catalyst", "new catalyst", "driving factor", "key driver",
    "催化", "催化劑", "正面消息", "利多",
}

# ---------------------------------------------------------------------------
# Family alias phrases (fix for review point 2 -- exact/curated matching
# only, no single generic-word substring matching).
# ---------------------------------------------------------------------------

FAMILY_ALIASES: dict[str, list[str]] = {
    "price_volume_structure": [
        "price_volume_structure", "price volume structure", "price/volume structure",
        "price-volume structure", "technical structure", "chart structure",
        "support and resistance", "股價結構", "價量結構", "技術結構", "支撐壓力",
    ],
    "valuation": [
        "valuation", "估值", "本益比", "股價淨值比", "pe ratio", "p/e ratio", "pb ratio", "p/b ratio",
    ],
    "revenue": [
        "revenue", "營收", "monthly revenue", "sales revenue",
    ],
    "institutional_flow": [
        "institutional flow", "institutional investor flow", "foreign investor flow",
        "foreign fund flow", "法人買賣超", "外資買賣超", "投信買賣超", "三大法人",
    ],
    "mops_material_information": [
        "mops filing", "material information disclosure", "material information filing",
        "公開資訊觀測站", "重大訊息", "重訊",
    ],
    "eps_revisions": [
        "eps revisions", "earnings revisions", "analyst estimate revisions",
        "盈餘預估修正", "獲利預估修正",
    ],
    "analyst_consensus": [
        "analyst consensus", "consensus estimate", "分析師共識",
    ],
    "industry_pricing": [
        "industry pricing", "industry price benchmark", "產業報價",
    ],
    "inventory_supply_demand": [
        "inventory supply demand", "inventory/supply/demand", "庫存供需",
    ],
    "broad_news_semantics": [
        "broad news semantics", "broad news sentiment", "新聞語意",
    ],
}

# Match standalone numeric values, but not lookback digits embedded in field
# names such as ret5_pct, foreign_mean20, support_low60.  Those digits name a
# window; they are not claimed packet values.
_NUMBER_RE = re.compile(r"(?<![A-Za-z0-9_])-?\d+(?:\.\d+)?(?![A-Za-z0-9_])")

_VALUATION_BENCHMARK_KEYS = {
    "peer_pe", "peer_pe_median", "historical_pe_band", "historical_pe_low",
    "historical_pe_high", "sector_median_pe", "peer_pb", "historical_pb_band",
}

_PRICE_ANCHOR_KEYS = {
    "current_price", "support_low5", "support_low10", "support_low20",
    "support_low60", "high20", "high60",
}


# ---------------------------------------------------------------------------
# Text-matching helpers
# ---------------------------------------------------------------------------


def _text_mentions_any_phrase(text: str, phrases: set[str]) -> list[str]:
    lowered = text.lower()
    return [p for p in phrases if p.lower() in lowered]


def _text_mentions_family(text_lower: str, family_id: str) -> bool:
    """Only matches on curated alias phrases for family_id (see
    FAMILY_ALIASES). Never matches on a single generic word."""
    aliases = FAMILY_ALIASES.get(family_id, [family_id.replace("_", " ")])
    return any(alias.lower() in text_lower for alias in aliases)


# ---------------------------------------------------------------------------
# Grounding helpers (numeric cross-check against raw packet evidence)
# ---------------------------------------------------------------------------


def _extract_numbers(text: str) -> list[float]:
    return [float(m) for m in _NUMBER_RE.findall(text)]


def _flatten_raw_values(raw_family: Any) -> list[float]:
    numbers: list[float] = []
    if isinstance(raw_family, bool):
        return numbers
    if isinstance(raw_family, (int, float)):
        numbers.append(float(raw_family))
    elif isinstance(raw_family, dict):
        for v in raw_family.values():
            numbers.extend(_flatten_raw_values(v))
    elif isinstance(raw_family, (list, tuple)):
        for v in raw_family:
            numbers.extend(_flatten_raw_values(v))
    elif isinstance(raw_family, str):
        numbers.extend(_extract_numbers(raw_family))
    return numbers


def _number_matches_any(claimed: float, raw_numbers: list[float], rel_tol: float = 0.01, abs_tol: float = 0.011) -> bool:
    for r in raw_numbers:
        if abs(claimed - r) <= max(abs_tol, abs(r) * rel_tol):
            return True
        if abs(claimed - r * 100) <= max(abs_tol, abs(r * 100) * rel_tol):
            return True
        if abs(claimed * 100 - r) <= max(abs_tol, abs(r) * rel_tol):
            return True
    return False


def _ground_numeric_claims(exact_observations: list[str], evidence_id: str, pkt_evidence: dict) -> list[str]:
    raw_family = pkt_evidence.get(evidence_id)
    if raw_family is None:
        return []
    raw_numbers = _flatten_raw_values(raw_family)
    if not raw_numbers:
        return []
    problems = []
    for obs_text in exact_observations:
        for claimed in _extract_numbers(obs_text):
            if not _number_matches_any(claimed, raw_numbers):
                problems.append(
                    f"exact_observations claim '{obs_text}' for evidence_id={evidence_id!r} contains "
                    f"number {claimed} not found in this family's raw packet data {raw_numbers}."
                )
    return problems


# ---------------------------------------------------------------------------
# Stage 1 validation
# ---------------------------------------------------------------------------


def validate_stage1_output(
    raw: Any,
    expected_case_id: int,
    case_available_evidence_ids: list[str],
    pkt_evidence: dict | None = None,
) -> tuple[dict, list[str]]:
    try:
        return _validate_stage1_output_impl(raw, expected_case_id, case_available_evidence_ids, pkt_evidence)
    except Exception as e:  # noqa: BLE001
        return {}, [f"Stage1 validator crashed on malformed input: {type(e).__name__}: {e}"]


def _validate_stage1_output_impl(
    raw: Any,
    expected_case_id: int,
    case_available_evidence_ids: list[str],
    pkt_evidence: dict | None,
) -> tuple[dict, list[str]]:
    errors: list[str] = []

    if not isinstance(raw, dict):
        return {}, [f"Stage1 output must be a JSON object, got {type(raw)}"]

    extra = set(raw.keys()) - {"case_id", "evidence_observations"}
    if extra:
        errors.append(f"Stage1 output has unexpected top-level key(s): {sorted(extra)}")
    missing = {"case_id", "evidence_observations"} - set(raw.keys())
    if missing:
        errors.append(f"Stage1 output missing key(s): {sorted(missing)}")
    if errors:
        return {}, errors

    returned_case_id = raw["case_id"]
    if not isinstance(returned_case_id, int) or isinstance(returned_case_id, bool) or returned_case_id != expected_case_id:
        return {}, [
            f"Stage1 output case_id={returned_case_id!r} (type={type(returned_case_id).__name__}) does not "
            f"match expected_case_id={expected_case_id!r}. This output cannot be trusted for any case."
        ]

    obs_list = raw["evidence_observations"]
    if not isinstance(obs_list, list) or not obs_list:
        return {}, ["Stage1 evidence_observations must be a non-empty list"]

    seen_ids: set[str] = set()
    normalized_obs = []
    for i, obs in enumerate(obs_list):
        prefix = f"evidence_observations[{i}]"
        if not isinstance(obs, dict):
            errors.append(f"{prefix} must be an object")
            continue

        required = {
            "evidence_id", "exact_observations", "direction", "timeliness",
            "relevance_to_hypothesis_space", "limitations", "benchmark_available",
        }
        extra_keys = set(obs.keys()) - required
        missing_keys = required - set(obs.keys())
        if extra_keys:
            errors.append(f"{prefix} has unexpected key(s): {sorted(extra_keys)}")
        if missing_keys:
            errors.append(f"{prefix} missing key(s): {sorted(missing_keys)}")
            continue

        eid = obs["evidence_id"]
        if not isinstance(eid, str):
            errors.append(f"{prefix}.evidence_id must be a string, got {type(eid).__name__}")
            continue
        if eid not in case_available_evidence_ids:
            errors.append(f"{prefix}.evidence_id={eid!r} is not in case_available_evidence_ids {case_available_evidence_ids}")
        if eid in seen_ids:
            errors.append(f"{prefix}.evidence_id={eid!r} is duplicated")
        seen_ids.add(eid)

        exact_obs = obs["exact_observations"]
        if not isinstance(exact_obs, list) or not exact_obs or not all(isinstance(x, str) for x in exact_obs):
            errors.append(f"{prefix}.exact_observations must be a non-empty list of strings")
            exact_obs = []

        direction = obs["direction"]
        if direction not in DIRECTION_VALUES:
            errors.append(f"{prefix}.direction={direction!r} not in {sorted(DIRECTION_VALUES)}")

        timeliness = obs["timeliness"]
        if timeliness not in TIMELINESS_VALUES:
            errors.append(f"{prefix}.timeliness={timeliness!r} not in {sorted(TIMELINESS_VALUES)}")

        relevance = obs["relevance_to_hypothesis_space"]
        if relevance not in RELEVANCE_VALUES:
            errors.append(f"{prefix}.relevance_to_hypothesis_space={relevance!r} not in {sorted(RELEVANCE_VALUES)}")

        limitations = obs["limitations"]
        if not isinstance(limitations, list) or not all(isinstance(x, str) for x in limitations):
            errors.append(f"{prefix}.limitations must be a list of strings")
            limitations = []

        benchmark_available = obs["benchmark_available"]
        if not isinstance(benchmark_available, bool):
            errors.append(f"{prefix}.benchmark_available must be boolean")

        # This is a packet fact, not a model judgment.  Without this check a
        # model can evade the valuation rule simply by echoing true.
        if eid == "valuation" and pkt_evidence is not None:
            raw_valuation = pkt_evidence.get("valuation")
            if isinstance(raw_valuation, dict):
                expected_benchmark = bool(_VALUATION_BENCHMARK_KEYS & set(raw_valuation))
                if benchmark_available is not expected_benchmark:
                    errors.append(
                        f"{prefix}.benchmark_available={benchmark_available!r} contradicts the raw "
                        f"valuation packet; expected {expected_benchmark!r} from explicit benchmark fields."
                    )

        # UNIFIED valuation rule (review point 3): no benchmark => must be
        # NOT_INTERPRETABLE. This is now the ONLY rule (Stage 1 prompt has
        # been updated to match; the old "absolute magnitude can still be
        # SUPPORTIVE/CONTRADICTORY" language is removed).
        if eid == "valuation" and benchmark_available is False:
            has_caveat = any("benchmark" in lim.lower() or "基準" in lim or "比較" in lim for lim in limitations)
            if not has_caveat:
                errors.append(
                    f"{prefix}: evidence_id='valuation' has benchmark_available=false but limitations "
                    f"does not state the no-benchmark caveat required by the contract."
                )
            if direction != "NOT_INTERPRETABLE":
                errors.append(
                    f"{prefix}: evidence_id='valuation' has benchmark_available=false, so direction must be "
                    f"'NOT_INTERPRETABLE' (an absolute PE/PB number alone, with no peer or historical "
                    f"comparison point, cannot support a SUPPORTIVE or CONTRADICTORY judgment). Got "
                    f"direction={direction!r}."
                )

        if pkt_evidence is not None and eid in case_available_evidence_ids and exact_obs:
            grounding_problems = _ground_numeric_claims(exact_obs, eid, pkt_evidence)
            errors.extend(f"{prefix}: {p}" for p in grounding_problems)

        normalized_obs.append(
            {
                "evidence_id": eid,
                "exact_observations": exact_obs,
                "direction": direction,
                "timeliness": timeliness,
                "relevance_to_hypothesis_space": relevance,
                "limitations": limitations,
                "benchmark_available": benchmark_available,
            }
        )

    missing_families = set(case_available_evidence_ids) - seen_ids
    if missing_families:
        errors.append(f"Stage1 output does not cover all case_available_evidence_ids; missing: {sorted(missing_families)}")

    normalized = {"case_id": returned_case_id, "evidence_observations": normalized_obs}
    return normalized, errors


# ---------------------------------------------------------------------------
# Stage 2a: decision-only validation (NO entry/failure_exit fields at all)
# ---------------------------------------------------------------------------


def validate_stage2_decision_output(raw: Any, stage1_observations: list[dict], pkt_evidence: dict) -> tuple[dict, list[str], list[str]]:
    try:
        return _validate_stage2_decision_output_impl(raw, stage1_observations, pkt_evidence)
    except Exception as e:  # noqa: BLE001
        return {}, [f"Stage2 decision validator crashed on malformed input: {type(e).__name__}: {e}"], []


def _as_str_list_safe(value: Any, field_name: str, errors: list[str]) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list):
        errors.append(f"'{field_name}' must be a list, got {type(value).__name__}: {value!r}")
        return []
    out = []
    for item in value:
        if not isinstance(item, str):
            errors.append(f"'{field_name}' must contain only strings, found {type(item).__name__}: {item!r}")
            continue
        out.append(item)
    return list(dict.fromkeys(out))


def _validate_stage2_decision_output_impl(raw: Any, stage1_observations: list[dict], pkt_evidence: dict) -> tuple[dict, list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []

    if not isinstance(raw, dict):
        return {}, [f"Stage2 decision output must be a JSON object, got {type(raw)}"], []

    required_top = {
        "decision", "evidence_quality", "hypothesis_type", "hypothesis",
        "primary_evidence_ids", "secondary_evidence_ids", "counter_evidence_ids",
        "system_limitations", "bull_thesis", "bear_thesis", "invalidation", "decision_reason",
    }
    extra = set(raw.keys()) - required_top
    missing = required_top - set(raw.keys())
    if extra:
        errors.append(
            f"Stage2 decision output has unexpected top-level key(s): {sorted(extra)}. "
            f"NOTE: entry/failure_exit do NOT belong in this response -- they are a separate call "
            f"made only when decision is CANDIDATE/HIGH_CONVICTION."
        )
    if missing:
        errors.append(f"Stage2 decision output missing key(s): {sorted(missing)}")
    if errors:
        return {}, errors, []

    for str_field in ("decision", "evidence_quality", "hypothesis_type", "hypothesis",
                       "bull_thesis", "bear_thesis", "invalidation", "decision_reason"):
        if not isinstance(raw.get(str_field), str):
            errors.append(f"'{str_field}' must be a string, got {type(raw.get(str_field)).__name__}")

    normalized = {
        "decision": raw.get("decision", "").strip().upper() if isinstance(raw.get("decision"), str) else "",
        "evidence_quality": raw.get("evidence_quality", "").strip().upper() if isinstance(raw.get("evidence_quality"), str) else "",
        "hypothesis_type": raw.get("hypothesis_type", "").strip() if isinstance(raw.get("hypothesis_type"), str) else "",
        "hypothesis": raw.get("hypothesis", "").strip() if isinstance(raw.get("hypothesis"), str) else "",
        "primary_evidence_ids": _as_str_list_safe(raw.get("primary_evidence_ids"), "primary_evidence_ids", errors),
        "secondary_evidence_ids": _as_str_list_safe(raw.get("secondary_evidence_ids"), "secondary_evidence_ids", errors),
        "counter_evidence_ids": _as_str_list_safe(raw.get("counter_evidence_ids"), "counter_evidence_ids", errors),
        "system_limitations": _as_str_list_safe(raw.get("system_limitations"), "system_limitations", errors),
        "bull_thesis": raw.get("bull_thesis", "").strip() if isinstance(raw.get("bull_thesis"), str) else "",
        "bear_thesis": raw.get("bear_thesis", "").strip() if isinstance(raw.get("bear_thesis"), str) else "",
        "invalidation": raw.get("invalidation", "").strip() if isinstance(raw.get("invalidation"), str) else "",
        "decision_reason": raw.get("decision_reason", "").strip() if isinstance(raw.get("decision_reason"), str) else "",
    }

    decision = normalized["decision"]
    evidence_quality = normalized["evidence_quality"]
    if decision not in DECISION_VALUES:
        errors.append(f"decision={decision!r} not in {sorted(DECISION_VALUES)}")
    if evidence_quality not in EVIDENCE_QUALITY_VALUES:
        errors.append(f"evidence_quality={evidence_quality!r} not in {sorted(EVIDENCE_QUALITY_VALUES)}")

    if decision in {"WATCH", "CANDIDATE", "HIGH_CONVICTION"} and not normalized["primary_evidence_ids"]:
        errors.append(
            f"decision={decision} requires at least one primary_evidence_id grounded in SUPPORTIVE/MIXED Stage1 evidence"
        )
    if decision == "HIGH_CONVICTION" and len(set(normalized["primary_evidence_ids"] + normalized["secondary_evidence_ids"])) < 2:
        errors.append(
            "decision=HIGH_CONVICTION requires at least two distinct SUPPORTIVE/MIXED evidence families"
        )

    obs_by_id = {o["evidence_id"]: o for o in stage1_observations if isinstance(o, dict) and isinstance(o.get("evidence_id"), str)}
    supportive_or_mixed = {eid for eid, o in obs_by_id.items() if o.get("direction") in ("SUPPORTIVE", "MIXED")}
    contradictory_or_mixed = {eid for eid, o in obs_by_id.items() if o.get("direction") in ("CONTRADICTORY", "MIXED")}
    contradictory_strict = {eid for eid, o in obs_by_id.items() if o.get("direction") == "CONTRADICTORY"}
    forbidden_role_families = {eid for eid, o in obs_by_id.items() if o.get("direction") in ("NEUTRAL", "NOT_INTERPRETABLE")}

    for fld in ("primary_evidence_ids", "secondary_evidence_ids", "counter_evidence_ids"):
        bad_forbidden = set(normalized[fld]) & forbidden_role_families
        if bad_forbidden:
            errors.append(
                f"{fld} contains id(s) with Stage1 direction NEUTRAL or NOT_INTERPRETABLE, which may "
                f"never be used as evidence for or against the thesis in any role: {sorted(bad_forbidden)}"
            )

    for fld in ("primary_evidence_ids", "secondary_evidence_ids"):
        bad = set(normalized[fld]) - supportive_or_mixed
        if bad:
            errors.append(f"{fld} contains id(s) not SUPPORTIVE/MIXED per Stage1: {sorted(bad)}")
    bad_counter = set(normalized["counter_evidence_ids"]) - contradictory_or_mixed
    if bad_counter:
        errors.append(f"counter_evidence_ids contains id(s) not CONTRADICTORY/MIXED per Stage1: {sorted(bad_counter)}")

    # NEW hard rule (review point 4): every strictly-CONTRADICTORY family
    # MUST be listed in counter_evidence_ids -- it is not optional.
    missing_required_counter = contradictory_strict - set(normalized["counter_evidence_ids"])
    if missing_required_counter:
        errors.append(
            f"counter_evidence_ids is missing required CONTRADICTORY family/families (Stage1 marked these "
            f"CONTRADICTORY; they must be listed, not silently dropped): {sorted(missing_required_counter)}"
        )

    evidence_sets = derive_case_evidence_sets(pkt_evidence)
    expected_system_unavailable = set(evidence_sets["system_unavailable_evidence_ids"])
    if set(normalized["system_limitations"]) != expected_system_unavailable:
        errors.append(
            f"system_limitations does not match system_unavailable_evidence_ids. "
            f"Expected {sorted(expected_system_unavailable)}, got {sorted(normalized['system_limitations'])}"
        )

    # System-unavailable families are transparency metadata only.  Keeping
    # them out of decision prose makes it mechanically impossible to use
    # their absence as a hidden justification for WATCH/REJECT.
    for fld in ("bull_thesis", "bear_thesis", "decision_reason"):
        text_lower = normalized[fld].lower()
        mentioned_system_limits = sorted(
            eid for eid in expected_system_unavailable
            if _text_mentions_family(text_lower, eid)
        )
        if mentioned_system_limits:
            errors.append(
                f"{fld} references system-unavailable family/families {mentioned_system_limits}; "
                f"system limitations belong only in system_limitations and may not support or oppose the decision."
            )

    bear_text_lower = normalized["bear_thesis"].lower()
    for eid in contradictory_or_mixed:
        if _text_mentions_family(bear_text_lower, eid) and eid not in normalized["counter_evidence_ids"]:
            errors.append(
                f"bear_thesis references evidence family '{eid}' (Stage1 direction={obs_by_id[eid]['direction']}) "
                f"but counter_evidence_ids does not include it."
            )
    if decision in NON_ACTIONABLE_DECISIONS and not normalized["counter_evidence_ids"]:
        if any(kw in bear_text_lower for kw in ("risk", "concern", "weak", "negative", "風險", "疑慮", "轉弱", "負向", "下滑")):
            warnings.append(
                "bear_thesis uses negative-sounding language but counter_evidence_ids is empty and no "
                "specific CONTRADICTORY/MIXED family was matched by name -- recommend human review."
            )

    for eid, obs in obs_by_id.items():
        if obs.get("benchmark_available") is False:
            for fld in ("bull_thesis", "bear_thesis", "decision_reason"):
                text_lower = normalized[fld].lower()
                if _text_mentions_family(text_lower, eid):
                    hits = _text_mentions_any_phrase(normalized[fld], VALUE_JUDGMENT_PHRASES)
                    if hits:
                        errors.append(f"{fld} makes a value judgment ({hits}) about '{eid}', which has benchmark_available=false.")

    for eid, obs in obs_by_id.items():
        has_single_period_caveat = any(
            "single-period" in lim.lower() or "single period" in lim.lower() or "單期" in lim
            for lim in obs.get("limitations", [])
        )
        if has_single_period_caveat:
            for fld in ("bull_thesis", "decision_reason"):
                text_lower = normalized[fld].lower()
                if _text_mentions_family(text_lower, eid):
                    hits = _text_mentions_any_phrase(normalized[fld], DURATIVE_TREND_PHRASES)
                    if hits:
                        errors.append(f"{fld} describes '{eid}' with durative/trend language ({hits}), but Stage1 flagged it as single-period.")

    for eid, obs in obs_by_id.items():
        has_routine_caveat = any(
            "routine" in lim.lower() or "periodic" in lim.lower() or "例行" in lim
            for lim in obs.get("limitations", [])
        )
        if has_routine_caveat:
            for fld in ("bull_thesis", "decision_reason"):
                text_lower = normalized[fld].lower()
                if _text_mentions_family(text_lower, eid):
                    hits = _text_mentions_any_phrase(normalized[fld], CATALYST_PHRASES)
                    if hits:
                        errors.append(f"{fld} describes '{eid}' as a catalyst ({hits}), but Stage1 flagged it as routine/periodic.")

    for eid, obs in obs_by_id.items():
        if obs.get("direction") == "MIXED":
            for fld in ("bull_thesis", "bear_thesis"):
                text_lower = normalized[fld].lower()
                if _text_mentions_family(text_lower, eid):
                    if any(kw in text_lower for kw in ("clearly positive", "uniformly positive", "全面正向", "全面看多", "clearly negative", "uniformly negative", "全面負向", "全面看空")):
                        warnings.append(f"{fld} describes MIXED-direction family '{eid}' in uniform terms.")

    for text_field in ("hypothesis", "bull_thesis", "bear_thesis", "invalidation", "decision_reason"):
        if not normalized[text_field]:
            errors.append(f"'{text_field}' must not be empty")

    return normalized, errors, warnings


# ---------------------------------------------------------------------------
# Stage 2b: actionability-only validation (entry/failure_exit ONLY; called
# exclusively when decision is CANDIDATE/HIGH_CONVICTION)
# ---------------------------------------------------------------------------


def validate_stage2_actionability_output(
    raw: Any,
    stage1_observations: list[dict],
    pkt_evidence: dict | None = None,
) -> tuple[dict, list[str]]:
    try:
        return _validate_stage2_actionability_output_impl(raw, stage1_observations, pkt_evidence)
    except Exception as e:  # noqa: BLE001
        return {}, [f"Stage2 actionability validator crashed on malformed input: {type(e).__name__}: {e}"]


def _validate_stage2_actionability_output_impl(
    raw: Any,
    stage1_observations: list[dict],
    pkt_evidence: dict | None,
) -> tuple[dict, list[str]]:
    errors: list[str] = []
    if not isinstance(raw, dict):
        return {}, [f"Stage2 actionability output must be a JSON object, got {type(raw)}"]

    extra = set(raw.keys()) - {"entry", "failure_exit"}
    missing = {"entry", "failure_exit"} - set(raw.keys())
    if extra:
        errors.append(f"Stage2 actionability output has unexpected top-level key(s): {sorted(extra)}")
    if missing:
        errors.append(f"Stage2 actionability output missing key(s): {sorted(missing)}")
    if errors:
        return {}, errors

    entry = raw.get("entry")
    failure_exit = raw.get("failure_exit")
    if not isinstance(entry, dict) or set(entry.keys()) != {"status", "ideal_low", "ideal_high"}:
        return {}, ["'entry' must be an object with exactly status/ideal_low/ideal_high"]
    if not isinstance(failure_exit, dict) or set(failure_exit.keys()) != {"exit_price", "reason", "trigger_type"}:
        return {}, ["'failure_exit' must be an object with exactly exit_price/reason/trigger_type"]

    status = entry.get("status", "").strip().upper() if isinstance(entry.get("status"), str) else entry.get("status")
    trigger_type = (
        failure_exit.get("trigger_type", "").strip().upper()
        if isinstance(failure_exit.get("trigger_type"), str) else failure_exit.get("trigger_type")
    )

    if status not in ENTRY_STATUS_ACTIONABLE_VALUES:
        errors.append(
            f"entry.status={status!r} not in {sorted(ENTRY_STATUS_ACTIONABLE_VALUES)}. This call is only made "
            f"for an actionable decision, so NOT_ACTIONABLE is not a valid answer here."
        )
    if trigger_type not in FAILURE_TRIGGER_ACTIONABLE_VALUES:
        errors.append(
            f"failure_exit.trigger_type={trigger_type!r} not in {sorted(FAILURE_TRIGGER_ACTIONABLE_VALUES)}. "
            f"UNAVAILABLE is not a valid answer here."
        )

    obs_by_id = {o["evidence_id"]: o for o in stage1_observations if isinstance(o, dict) and isinstance(o.get("evidence_id"), str)}
    price_family = obs_by_id.get("price_volume_structure")
    observed_price_numbers: list[float] = []
    if price_family:
        for txt in price_family.get("exact_observations", []):
            observed_price_numbers.extend(_extract_numbers(txt))

    # Prefer packet-owned named price anchors.  Returns, volume ratios and
    # ATR values must not widen the admissible price range accidentally.
    raw_price_family = (pkt_evidence or {}).get("price_volume_structure")
    price_anchors: list[float] = []
    atr = 0.0
    if isinstance(raw_price_family, dict):
        for key in _PRICE_ANCHOR_KEYS:
            value = raw_price_family.get(key)
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                price_anchors.append(float(value))
        atr_value = raw_price_family.get("atr20")
        if isinstance(atr_value, (int, float)) and not isinstance(atr_value, bool):
            atr = max(0.0, float(atr_value))
    if not price_anchors:
        price_anchors = observed_price_numbers

    plausible_low = max(0.0, min(price_anchors) - 2.0 * atr) if price_anchors else None
    plausible_high = max(price_anchors) + 2.0 * atr if price_anchors else None

    il, ih = entry.get("ideal_low"), entry.get("ideal_high")
    if il is None or ih is None:
        errors.append("entry.ideal_low/ideal_high must both be non-null real numbers for an actionable decision")
    elif isinstance(il, bool) or isinstance(ih, bool) or not isinstance(il, (int, float)) or not isinstance(ih, (int, float)):
        errors.append("entry.ideal_low/ideal_high must be numeric")
    else:
        if il > ih:
            errors.append(f"entry.ideal_low ({il}) must be <= entry.ideal_high ({ih})")
        if plausible_low is not None and plausible_high is not None:
            if not (plausible_low <= il <= plausible_high) or not (plausible_low <= ih <= plausible_high):
                errors.append(
                    f"entry.ideal_low/ideal_high ({il}/{ih}) is not within a plausible range of the "
                    f"packet price anchors ({price_anchors}); allowed envelope is "
                    f"[{plausible_low}, {plausible_high}]."
                )

    exit_price = failure_exit.get("exit_price")
    if exit_price is None:
        errors.append("failure_exit.exit_price must be a non-null real number for an actionable decision")
    elif isinstance(exit_price, bool) or not isinstance(exit_price, (int, float)):
        errors.append("failure_exit.exit_price must be numeric")
    elif plausible_low is not None and plausible_high is not None:
        if not (plausible_low <= exit_price <= plausible_high):
            errors.append(
                f"failure_exit.exit_price ({exit_price}) is not within the packet price-anchor envelope "
                f"[{plausible_low}, {plausible_high}]."
            )
        if isinstance(il, (int, float)) and not isinstance(il, bool) and exit_price >= il:
            errors.append(
                f"failure_exit.exit_price ({exit_price}) must be below entry.ideal_low ({il}) for a long-only actionable plan."
            )

    reason = failure_exit.get("reason")
    if not isinstance(reason, str) or not reason.strip():
        errors.append("failure_exit.reason must be a non-empty string")

    normalized = {
        "entry": {"status": status, "ideal_low": il, "ideal_high": ih},
        "failure_exit": {"exit_price": exit_price, "reason": reason if isinstance(reason, str) else None, "trigger_type": trigger_type},
    }
    return normalized, errors


# ---------------------------------------------------------------------------
# Stage 3 validation
# ---------------------------------------------------------------------------


def validate_stage3_output(raw: Any, stage1_evidence_ids: list[str] | None = None) -> tuple[dict, list[str]]:
    try:
        return _validate_stage3_output_impl(raw, stage1_evidence_ids or [])
    except Exception as e:  # noqa: BLE001
        return {}, [f"Stage3 validator crashed on malformed input: {type(e).__name__}: {e}"]


def _validate_stage3_output_impl(raw: Any, stage1_evidence_ids: list[str]) -> tuple[dict, list[str]]:
    errors: list[str] = []
    if not isinstance(raw, dict):
        return {}, [f"Stage3 output must be a JSON object, got {type(raw)}"]

    extra = set(raw.keys()) - {"verdict", "problems"}
    missing = {"verdict", "problems"} - set(raw.keys())
    if extra:
        errors.append(f"Stage3 output has unexpected top-level key(s): {sorted(extra)}")
    if missing:
        errors.append(f"Stage3 output missing key(s): {sorted(missing)}")
    if errors:
        return {}, errors

    verdict = raw["verdict"]
    if verdict not in CRITIC_VERDICT_VALUES:
        errors.append(f"verdict={verdict!r} not in {sorted(CRITIC_VERDICT_VALUES)}")

    problems = raw["problems"]
    if not isinstance(problems, list):
        return {}, [f"'problems' must be a list, got {type(problems).__name__}"]

    normalized_problems = []
    for i, p in enumerate(problems):
        prefix = f"problems[{i}]"
        if not isinstance(p, dict):
            errors.append(f"{prefix} must be an object, got {type(p).__name__}")
            continue
        if set(p.keys()) != CRITIC_PROBLEM_REQUIRED_KEYS:
            errors.append(f"{prefix} keys must be exactly {sorted(CRITIC_PROBLEM_REQUIRED_KEYS)}, got {sorted(p.keys())}")
            continue

        field_val, claim_text, cited_evidence_id = p["field"], p["claim_text"], p["cited_evidence_id"]
        problem_type, explanation = p["problem_type"], p["explanation"]
        ok = True

        if field_val not in CRITIC_PROBLEM_FIELD_VALUES:
            errors.append(f"{prefix}.field={field_val!r} not in {sorted(CRITIC_PROBLEM_FIELD_VALUES)}")
            ok = False
        if not isinstance(claim_text, str) or not claim_text.strip():
            errors.append(f"{prefix}.claim_text must be a non-empty string, got {claim_text!r}")
            ok = False
        if cited_evidence_id is not None:
            if not isinstance(cited_evidence_id, str):
                errors.append(f"{prefix}.cited_evidence_id must be null or a string, got {type(cited_evidence_id).__name__}: {cited_evidence_id!r}")
                ok = False
            elif stage1_evidence_ids and cited_evidence_id not in stage1_evidence_ids:
                errors.append(f"{prefix}.cited_evidence_id={cited_evidence_id!r} is not one of Stage1's evidence_ids {stage1_evidence_ids}")
                ok = False
        if problem_type not in CRITIC_PROBLEM_TYPES:
            errors.append(f"{prefix}.problem_type={problem_type!r} not in {sorted(CRITIC_PROBLEM_TYPES)}")
            ok = False
        if not isinstance(explanation, str) or not explanation.strip():
            errors.append(f"{prefix}.explanation must be a non-empty string, got {explanation!r}")
            ok = False

        if ok:
            normalized_problems.append(p)

    if verdict == "APPROVE" and normalized_problems:
        errors.append("verdict=APPROVE but problems is non-empty; these are contradictory")
    if verdict == "REVISE" and not normalized_problems and not errors:
        errors.append("verdict=REVISE but problems is empty (or none were valid); must list at least one concrete problem")

    return {"verdict": verdict, "problems": normalized_problems}, errors


# ---------------------------------------------------------------------------
# Structured repair requests (review point 5)
# ---------------------------------------------------------------------------

_ENUM_PATTERN = re.compile(r"^(?P<field>[\w.]+)=(?P<received>.+?) not in (?P<allowed>\[.+\])\.?$")
_ID_LIST_PATTERN = re.compile(r"^(?P<field>\w+) contains id\(s\) (?P<problem>not \w+(?:/\w+)? per Stage1): (?P<received>\[.+\])$")
_MISSING_COUNTER_PATTERN = re.compile(r"^counter_evidence_ids is missing required CONTRADICTORY family/families.*?: (?P<missing>\[.+\])$")
_SYSTEM_LIMITATIONS_PATTERN = re.compile(r"^system_limitations does not match system_unavailable_evidence_ids\. Expected (?P<expected>\[.+?\]), got (?P<received>\[.+\])$")
_EMPTY_FIELD_PATTERN = re.compile(r"^'(?P<field>\w+)' must not be empty$")
_MISSING_KEY_PATTERN = re.compile(r"^Stage2 (?:decision|actionability) output missing key\(s\): (?P<keys>\[.+\])$")
_UNEXPECTED_KEY_PATTERN = re.compile(r"^Stage2 (?:decision|actionability) output has unexpected top-level key\(s\): (?P<keys>\[.+?\])")


def errors_to_repair_request(errors: list[str]) -> list[dict]:
    """
    Converts this module's own human-readable error strings into a compact
    list of {field, problem, received, allowed} dicts, for the subset of
    error shapes this module itself generates in a fixed, enumerable
    format (which is most of them, since they all come from this file).
    Any error string that doesn't match a known pattern is passed through
    as {"field": "unspecified", "problem": <the raw string>}, so nothing
    is silently dropped -- the structured list is a SUPPLEMENT to the raw
    errors sent to the model, never a replacement that could hide
    something.
    """
    repairs: list[dict] = []
    for e in errors:
        m = _ENUM_PATTERN.match(e)
        if m:
            repairs.append({
                "field": m.group("field"), "problem": "invalid_enum_value",
                "received": m.group("received"), "allowed": m.group("allowed"),
            })
            continue
        m = _ID_LIST_PATTERN.match(e)
        if m:
            repairs.append({
                "field": m.group("field"), "problem": m.group("problem"),
                "received": m.group("received"), "instruction": "remove these ids from this field",
            })
            continue
        m = _MISSING_COUNTER_PATTERN.match(e)
        if m:
            repairs.append({
                "field": "counter_evidence_ids", "problem": "missing_required_contradictory_family",
                "must_add": m.group("missing"),
            })
            continue
        m = _SYSTEM_LIMITATIONS_PATTERN.match(e)
        if m:
            repairs.append({
                "field": "system_limitations", "problem": "must_exactly_equal_system_unavailable_ids",
                "expected": m.group("expected"), "received": m.group("received"),
            })
            continue
        m = _EMPTY_FIELD_PATTERN.match(e)
        if m:
            repairs.append({"field": m.group("field"), "problem": "must_not_be_empty"})
            continue
        m = _MISSING_KEY_PATTERN.match(e)
        if m:
            repairs.append({"field": "top_level", "problem": "missing_required_keys", "missing": m.group("keys")})
            continue
        m = _UNEXPECTED_KEY_PATTERN.match(e)
        if m:
            repairs.append({"field": "top_level", "problem": "unexpected_keys_present", "received": m.group("keys")})
            continue
        if "value judgment" in e:
            repairs.append({"field": "unspecified", "problem": "value_judgment_without_benchmark", "detail": e})
            continue
        if "durative/trend language" in e:
            repairs.append({"field": "unspecified", "problem": "single_period_described_as_trend", "detail": e})
            continue
        if "as a catalyst" in e:
            repairs.append({"field": "unspecified", "problem": "routine_filing_described_as_catalyst", "detail": e})
            continue
        if "not within a plausible range" in e:
            repairs.append({"field": "unspecified", "problem": "price_not_grounded_in_evidence", "detail": e})
            continue
        if "NEUTRAL or NOT_INTERPRETABLE" in e:
            repairs.append({"field": "unspecified", "problem": "forbidden_role_family_used", "detail": e})
            continue
        repairs.append({"field": "unspecified", "problem": e})
    return repairs
