#!/usr/bin/env python3
"""Corrected low-base persistence test.

Important correction: recommendation counts are generated by an execution-independent
shadow R10 ranking. They do NOT depend on whether the portfolio actually bought the
stock, available slots, cash, or holdings. This is the correct way to test 'wait for
2nd/3rd recommendation before buying'.

A low-base watch starts when a stock is in the daily shadow recommendation set while
meeting the pre-registered low-base/base-completed structure. Subsequent shadow
recommendations within the window count even if the stock has begun to lift from the
base. The actual locked R10 portfolio is then allowed to submit the BUY only once the
shadow count reaches the required threshold. Non-low-base names retain normal R10
first-signal entry behavior.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path
import numpy as np
import pandas as pd

import backtest_r10_persistence_gate as base

ROOT = Path(__file__).resolve().parents[1]
RUN_ROOT = ROOT / "lowbase_shadow_results"
BASELINE_DIR = RUN_ROOT / "baseline"
VARIANTS = [
    {"name": "SHADOW_LB_P2_5", "min_count": 2, "window": 5},
    {"name": "SHADOW_LB_P2_10", "min_count": 2, "window": 10},
    {"name": "SHADOW_LB_P3_5", "min_count": 3, "window": 5},
    {"name": "SHADOW_LB_P3_10", "min_count": 3, "window": 10},
]


def build_runner(locked_source: str, cfg: dict) -> str:
    marker = (
        "# ============================================================\n"
        "# 步驟三：組合層回測引擎\n"
        "# ============================================================\n\n"
    )
    stage3 = locked_source.split(marker, 1)[1]
    old_load = "px = pd.read_pickle('r10max_signals_final.pkl').sort_values(['date', 'code']).reset_index(drop=True)"
    new_load = (
        "px = pd.read_pickle('../baseline/r10max_signals_final.pkl').sort_values(['date', 'code']).reset_index(drop=True)\n"
        "px['research_high120'] = px.groupby('code')['aclose'].transform(lambda s: s.rolling(120, min_periods=120).max())"
    )
    if old_load not in stage3:
        raise RuntimeError("signal-load anchor not found")
    stage3 = stage3.replace(old_load, new_load, 1)

    state_anchor = "cash = INITIAL_CAPITAL\n"
    if state_anchor not in stage3:
        raise RuntimeError("cash-state anchor not found")

    injection = f'''# ---- Corrected execution-independent shadow recommendation layer ----
PERSISTENCE_MIN_COUNT = {int(cfg['min_count'])}
PERSISTENCE_WINDOW = {int(cfg['window'])}
shadow_state = {{}}
shadow_rows = []
watch_hist = {{}}


def lowbase_completed(r):
    vals = [r.get('aclose', np.nan), r.get('ma20', np.nan), r.get('ma60', np.nan),
            r.get('ma120', np.nan), r.get('research_high120', np.nan)]
    if not all(np.isfinite(v) and v > 0 for v in vals):
        return False
    aclose, ma20, ma60, ma120, high120 = map(float, vals)
    return bool(
        aclose <= 0.90 * high120 and
        aclose >= ma60 and
        ma20 >= ma60 and
        aclose >= 0.98 * ma120 and
        ma60 <= 1.05 * ma120
    )

# Build a daily shadow recommendation set as though no stock were already held.
# It uses only the locked R10 daily hard filters/ranks/regime. No cash/position state.
for _d in all_dates:
    _i = date_idx[_d]
    _sub = by_date.get(_d)
    if _sub is None or len(_sub) == 0:
        continue
    _r7_exp = float(_sub['r7_exposure'].iloc[0]) if np.isfinite(_sub['r7_exposure'].iloc[0]) else 0.0
    _r7_slots = int(_sub['r7_slots'].iloc[0]) if np.isfinite(_sub['r7_slots'].iloc[0]) else 0
    _r7 = (_sub[_sub['r7_hard'] == True].sort_values('r7_score', ascending=False).head(_r7_slots)
           if _r7_exp > 0 else _sub.iloc[0:0])
    _r05 = _sub[_sub['r05_hard'] == True].sort_values('r05_score', ascending=False).head(R05_MAX_SLOTS)
    _combined = [('R7', c, r) for c, r in _r7.iterrows()] + [('R05', c, r) for c, r in _r05.iterrows()]
    _combined.sort(key=lambda z: -(z[2]['r7_score'] if z[0] == 'R7' else z[2]['r05_score']))
    _seen = set(); _daily = []
    for _strat, _code, _r in _combined:
        _code = str(_code)
        if _code in _seen:
            continue
        _seen.add(_code); _daily.append((_strat, _code, _r))
        if len(_daily) >= MAX_POSITIONS:
            break

    # Expire stale watches before processing today's independent shadow list.
    for _code in list(watch_hist):
        _hist = [x for x in watch_hist[_code] if _i - x < PERSISTENCE_WINDOW]
        if _hist:
            watch_hist[_code] = _hist
        else:
            del watch_hist[_code]

    for _strat, _code, _r in _daily:
        _is_lb_now = lowbase_completed(_r)
        if _code not in watch_hist:
            if not _is_lb_now:
                shadow_rows.append({{'date': _d, 'code': _code, 'strategy': _strat,
                                    'lowbase_watch': False, 'is_lowbase_now': False,
                                    'count': 0, 'accepted': True}})
                continue
            watch_hist[_code] = []
        _hist = watch_hist[_code]
        if not _hist or _hist[-1] != _i:
            _hist.append(_i)
        _hist[:] = [x for x in _hist if _i - x < PERSISTENCE_WINDOW]
        _count = len(_hist)
        shadow_state[(_d, _code)] = {{'count': _count, 'watch_start': _hist[0],
                                      'is_lowbase_now': bool(_is_lb_now), 'strategy': _strat}}
        shadow_rows.append({{'date': _d, 'code': _code, 'strategy': _strat,
                            'lowbase_watch': True, 'is_lowbase_now': bool(_is_lb_now),
                            'count': _count, 'accepted': bool(_count >= PERSISTENCE_MIN_COUNT)}})

cash = INITIAL_CAPITAL
'''
    stage3 = stage3.replace(state_anchor, injection, 1)

    gate_anchor = (
        "                if post_total > TOTAL_CAP + 1e-12 or post_code > SINGLE_CAP + 1e-12: continue\n"
        "                o = submit('BUY', di, exdate, code, strat, shares, 'ENTRY', limit,\n"
    )
    gate_replacement = (
        "                if post_total > TOTAL_CAP + 1e-12 or post_code > SINGLE_CAP + 1e-12: continue\n"
        "                _ss = shadow_state.get((di, str(code)))\n"
        "                if _ss is not None and int(_ss['count']) < PERSISTENCE_MIN_COUNT:\n"
        "                    # Block only the watched low-base name. Preserve original slot opportunity; no backfill.\n"
        "                    used.add(code); slots_free -= 1\n"
        "                    continue\n"
        "                o = submit('BUY', di, exdate, code, strat, shares, 'ENTRY', limit,\n"
    )
    if gate_anchor not in stage3:
        raise RuntimeError("BUY anchor not found")
    stage3 = stage3.replace(gate_anchor, gate_replacement, 1)

    dump_anchor = "Path('contract_audit.json').write_text(json.dumps(audit, ensure_ascii=False, indent=2), encoding='utf-8')\n"
    if dump_anchor not in stage3:
        raise RuntimeError("dump anchor not found")
    stage3 = stage3.replace(
        dump_anchor,
        dump_anchor + "pd.DataFrame(shadow_rows).to_csv('shadow_recommendations.csv', index=False)\n",
        1,
    )

    return "# Generated corrected shadow-persistence runner.\nimport pandas as pd\nimport numpy as np\nimport json\nfrom pathlib import Path\n\n" + stage3


def main():
    if base.sha256(base.LOCKED_ENGINE) != base.LOCKED_ENGINE_SHA256:
        raise RuntimeError("locked R10 engine fingerprint mismatch")
    if RUN_ROOT.exists():
        shutil.rmtree(RUN_ROOT)
    RUN_ROOT.mkdir(parents=True)
    base.RUN_ROOT = RUN_ROOT
    base.BASELINE_DIR = BASELINE_DIR
    base.link_inputs(BASELINE_DIR)
    baseline_script = BASELINE_DIR / "r10_max_formal_locked.py"
    baseline_script.write_text(base.LOCKED_ENGINE.read_text(encoding="utf-8"), encoding="utf-8")
    base.run_python(baseline_script, BASELINE_DIR, "execution.log")
    base.verify_baseline()

    locked_source = base.LOCKED_ENGINE.read_text(encoding="utf-8")
    for cfg in VARIANTS:
        rd = RUN_ROOT / cfg['name']; rd.mkdir(parents=True)
        runner = rd / "runner.py"
        runner.write_text(build_runner(locked_source, cfg), encoding="utf-8")
        base.run_python(runner, rd, "execution.log")

    causal = pd.read_csv(BASELINE_DIR / "ohlcv_causal_2020_2025.csv.gz", dtype={'code': str},
                         usecols=lambda c: c in {'date','code','close','aclose','alow','ahigh'}, low_memory=False)
    causal['code'] = causal['code'].astype(str).str.zfill(4); causal['date'] = causal['date'].astype(int)
    rows = [base.collect_metrics('BASELINE', BASELINE_DIR, None, causal)]
    for cfg in VARIANTS:
        rd = RUN_ROOT / cfg['name']
        row = base.collect_metrics(cfg['name'], rd, cfg, causal)
        sh = pd.read_csv(rd / 'shadow_recommendations.csv', dtype={'code': str})
        watched = sh[sh['lowbase_watch'].astype(bool)]
        row['shadow_lowbase_observations'] = int(len(watched))
        row['shadow_lowbase_unique_codes'] = int(watched.code.nunique()) if len(watched) else 0
        row['shadow_count_ge2'] = int((watched['count'] >= 2).sum()) if len(watched) else 0
        row['shadow_count_ge3'] = int((watched['count'] >= 3).sum()) if len(watched) else 0
        rows.append(row)
    out = pd.DataFrame(rows)
    out.to_csv(RUN_ROOT / 'LOWBASE_SHADOW_COMPARISON.csv', index=False)
    (RUN_ROOT / 'LOWBASE_SHADOW_COMPARISON.json').write_text(
        json.dumps(out.replace({np.nan: None}).to_dict(orient='records'), ensure_ascii=False, indent=2), encoding='utf-8')
    print('=== CORRECTED LOW-BASE SHADOW PERSISTENCE ===')
    print(out[['variant','end_nav','cagr','max_drawdown','pnl_profit_factor','win_rate','completed_trades',
               'shadow_lowbase_observations','shadow_lowbase_unique_codes','shadow_count_ge2','shadow_count_ge3']].to_string(index=False))

if __name__ == '__main__':
    main()
