"""Research-only execution overlay for locked R10 MAX.

This script DOES NOT modify the locked strategy. It tests whether T+1 early-session
price deterioration contains information that the prior-close entry thesis has failed.

Inputs (generated by the locked formal engine):
  formal_run/r10max_formal_orders.csv
  formal_run/r10max_formal_trades.csv
  formal_run/ohlcv_causal_2020_2025.csv.gz

Minute source: FinMind TaiwanStockKBar (1-minute OHLCV).
The dataset is sponsor-gated; FINMIND_TOKEN should be supplied as a GitHub secret.

Outputs:
  research_out/minute_data_gate.json
  research_out/minute_features.csv
  research_out/entry_gate_grid.csv
  research_out/threshold_summary.csv

The grid is diagnostic only. Any promising gate must later be integrated into a
portfolio-level causal backtest before it can become a live rule.
"""
from __future__ import annotations

import json
import os
import time
from pathlib import Path

import numpy as np
import pandas as pd
import requests

OUT = Path("research_out")
OUT.mkdir(exist_ok=True)

ORDERS = Path("formal_run/r10max_formal_orders.csv")
TRADES = Path("formal_run/r10max_formal_trades.csv")
DAILY = Path("formal_run/ohlcv_causal_2020_2025.csv.gz")

for p in (ORDERS, TRADES, DAILY):
    if not p.exists():
        raise FileNotFoundError(p)

orders = pd.read_csv(ORDERS, dtype={"code": str})
trades = pd.read_csv(TRADES, dtype={"code": str})
daily = pd.read_csv(DAILY, dtype={"code": str}, low_memory=False)
orders["code"] = orders["code"].str.zfill(4)
trades["code"] = trades["code"].str.zfill(4)
daily["code"] = daily["code"].str.zfill(4)

# Use only actual filled entries from the frozen 2021-2025 test. This avoids
# treating repeated unfilled attempts as independent signals in the first diagnostic.
buys = orders[(orders.side == "BUY") & (orders.status == "FILLED")].copy()
buys["scheduled_date"] = buys["scheduled_date"].astype(int)
buys["signal_date"] = buys["signal_date"].astype(int)
buys["fill_date"] = buys["fill_date"].astype(int)
buys = buys[(buys.scheduled_date >= 20210101) & (buys.scheduled_date <= 20251231)]

# Attach the matching completed trade (same code / strategy / entry date).
trades["entry_date"] = trades["entry_date"].astype(int)
trades["exit_date"] = trades["exit_date"].astype(int)
keep_trade = ["code", "strategy", "entry_date", "exit_date", "exit_raw_price", "return", "reason"]
buys = buys.merge(
    trades[keep_trade],
    left_on=["code", "strategy", "fill_date"],
    right_on=["code", "strategy", "entry_date"],
    how="left",
    validate="many_to_one",
)
if buys["exit_date"].isna().any():
    missing = buys.loc[buys.exit_date.isna(), ["code", "strategy", "fill_date"]]
    raise RuntimeError(f"Could not map filled BUY orders to completed trades: {missing.to_dict('records')[:10]}")

# Signal-day close is the causal reference available at T close.
ref = daily[["date", "code", "close"]].copy()
ref["date"] = ref["date"].astype(int)
ref = ref.rename(columns={"date": "signal_date", "close": "signal_close"})
buys = buys.merge(ref, on=["signal_date", "code"], how="left", validate="many_to_one")
if buys.signal_close.isna().any():
    raise RuntimeError("Missing signal-date close for some BUY orders")

TOKEN = os.getenv("FINMIND_TOKEN", "").strip()
URL = "https://api.finmindtrade.com/api/v4/data"
SESSION = requests.Session()
if TOKEN:
    SESSION.headers.update({"Authorization": f"Bearer {TOKEN}"})


def fetch_kbar(code: str, ymd: int) -> tuple[pd.DataFrame | None, dict | None]:
    d = pd.to_datetime(str(ymd)).strftime("%Y-%m-%d")
    params = {"dataset": "TaiwanStockKBar", "data_id": code, "start_date": d}
    for attempt in range(4):
        try:
            r = SESSION.get(URL, params=params, timeout=30)
            try:
                payload = r.json()
            except Exception:
                payload = None
            if r.status_code == 200 and isinstance(payload, dict) and payload.get("status") == 200:
                df = pd.DataFrame(payload.get("data", []))
                if not df.empty:
                    return df, None
                return None, {"code": code, "date": int(ymd), "http": r.status_code,
                              "status": payload.get("status"), "msg": "empty data"}
            msg = payload.get("msg") if isinstance(payload, dict) else r.text[:300]
            # auth/tier/quota errors will not improve by retrying.
            if r.status_code in (401, 402, 403):
                return None, {"code": code, "date": int(ymd), "http": r.status_code,
                              "status": payload.get("status") if isinstance(payload, dict) else None,
                              "msg": msg}
        except Exception as e:
            msg = repr(e)
        time.sleep(1.5 * (attempt + 1))
    return None, {"code": code, "date": int(ymd), "http": None, "status": None, "msg": msg}


def first_or_nan(s: pd.Series):
    return s.iloc[0] if len(s) else np.nan

features = []
errors = []
for i, row in buys.sort_values(["scheduled_date", "code"]).iterrows():
    code = row.code
    ymd = int(row.scheduled_date)
    kb, err = fetch_kbar(code, ymd)
    if err:
        errors.append(err)
        # Fail early on entitlement/auth error so the workflow tells us exactly what is missing.
        if err.get("http") in (401, 402, 403):
            break
        continue
    kb["minute"] = kb["minute"].astype(str)
    for c in ["open", "high", "low", "close", "volume"]:
        kb[c] = pd.to_numeric(kb[c], errors="coerce")
    kb = kb.sort_values("minute")
    early = kb[(kb.minute >= "09:00:00") & (kb.minute <= "09:30:00")]
    if early.empty:
        errors.append({"code": code, "date": ymd, "msg": "no 09:00-09:30 rows"})
        continue
    out = {
        "code": code,
        "strategy": row.strategy,
        "signal_date": int(row.signal_date),
        "scheduled_date": ymd,
        "signal_close": float(row.signal_close),
        "limit_price": float(row.limit_price),
        "original_fill_price": float(row.raw_fill_price),
        "original_exit_date": int(row.exit_date),
        "original_exit_price": float(row.exit_raw_price),
        "original_return": float(row["return"]),
        "original_exit_reason": row.reason,
        "open_0900": float(early.iloc[0].open),
        "low_0900_0930": float(early.low.min()),
        "high_0900_0930": float(early.high.max()),
    }
    for m in (0, 5, 10, 15, 20, 30):
        t = f"09:{m:02d}:00"
        sub = kb[kb.minute == t]
        out[f"close_{m:02d}"] = float(first_or_nan(sub.close))
        seen = early[early.minute <= t]
        out[f"min_to_{m:02d}"] = float(seen.low.min()) if len(seen) else np.nan
        out[f"max_to_{m:02d}"] = float(seen.high.max()) if len(seen) else np.nan
    features.append(out)
    # keep request rate polite even with token
    time.sleep(0.05)

feat = pd.DataFrame(features)
feat.to_csv(OUT / "minute_features.csv", index=False)

gate = {
    "source": "FinMind TaiwanStockKBar",
    "token_present": bool(TOKEN),
    "requested": int(len(buys)),
    "received": int(len(feat)),
    "errors": errors[:20],
}
if errors and any(e.get("http") in (401, 402, 403) for e in errors):
    gate["status"] = "MINUTE_DATA_ENTITLEMENT_FAIL"
elif len(feat) != len(buys):
    gate["status"] = "MINUTE_DATA_INCOMPLETE"
else:
    gate["status"] = "PASS"
(OUT / "minute_data_gate.json").write_text(json.dumps(gate, ensure_ascii=False, indent=2), encoding="utf-8")

if gate["status"] != "PASS":
    print(json.dumps(gate, ensure_ascii=False, indent=2))
    raise SystemExit(20)

# ---------------------------------------------------------------------------
# Diagnostic grid:
# 1) wait until 09:05/10/15/20/30;
# 2) if the minimum traded price since 09:00 has fallen X% or more vs T close,
#    treat the prior-close thesis as invalid and cancel the BUY;
# 3) otherwise activate the ORIGINAL frozen limit from that minute onward;
# 4) fill approximation from 1-min bar: if bar open <= limit, fill at bar open;
#    else if bar low <= limit, fill at limit. No chasing above limit.
# 5) exit at the original frozen strategy exit price/date. This is a diagnostic,
#    not yet a portfolio-level re-backtest.
# ---------------------------------------------------------------------------
thresholds = [0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.095]
waits = [0, 5, 10, 15, 20, 30]
rows = []

# Re-fetch only from local features is insufficient to know post-wait first-touch of limit.
# Make one second pass, cached in-memory per trade; total requests stays < 300 for 150 trades.
kbar_cache = {}
for _, r in feat.iterrows():
    kb, err = fetch_kbar(r.code, int(r.scheduled_date))
    if err:
        raise RuntimeError(f"Second-pass KBar fetch failed: {err}")
    kb["minute"] = kb["minute"].astype(str)
    for c in ["open", "high", "low", "close"]:
        kb[c] = pd.to_numeric(kb[c], errors="coerce")
    kbar_cache[(r.code, int(r.scheduled_date))] = kb.sort_values("minute")
    time.sleep(0.05)

for wait in waits:
    start_t = f"09:{wait:02d}:00"
    min_col = f"min_to_{wait:02d}"
    for th in thresholds:
        sample = []
        for _, r in feat.iterrows():
            drop = r[min_col] / r.signal_close - 1.0
            invalid = bool(drop <= -th)
            fill = np.nan
            if not invalid:
                kb = kbar_cache[(r.code, int(r.scheduled_date))]
                after = kb[(kb.minute >= start_t) & (kb.minute <= "13:30:00")]
                limit = float(r.limit_price)
                hit = after[after.low <= limit]
                if len(hit):
                    b = hit.iloc[0]
                    fill = float(b.open) if b.open <= limit else limit
            if np.isfinite(fill):
                ret = float(r.original_exit_price) / fill - 1.0
                sample.append((False, True, ret, drop, fill))
            else:
                sample.append((invalid, False, np.nan, drop, np.nan))
        s = pd.DataFrame(sample, columns=["invalidated", "filled", "return_diag", "early_drop", "sim_fill"])
        kept = s[s.filled]
        rows.append({
            "wait_min": wait,
            "threshold": th,
            "signals": len(s),
            "invalidated": int(s.invalidated.sum()),
            "filled_after_gate": int(s.filled.sum()),
            "unfilled_after_wait": int((~s.invalidated & ~s.filled).sum()),
            "win_rate_diag": float((kept.return_diag > 0).mean()) if len(kept) else np.nan,
            "mean_return_diag": float(kept.return_diag.mean()) if len(kept) else np.nan,
            "median_return_diag": float(kept.return_diag.median()) if len(kept) else np.nan,
            "worst_return_diag": float(kept.return_diag.min()) if len(kept) else np.nan,
            "sum_return_diag": float(kept.return_diag.sum()) if len(kept) else np.nan,
        })

grid = pd.DataFrame(rows)
grid.to_csv(OUT / "entry_gate_grid.csv", index=False)

# Threshold-only summary independent of delayed fill: does an early breach identify bad trades?
summ = []
for wait in waits:
    col = f"min_to_{wait:02d}"
    for th in thresholds:
        bad = feat[col] / feat.signal_close - 1 <= -th
        a = feat[bad]
        b = feat[~bad]
        summ.append({
            "wait_min": wait,
            "threshold": th,
            "breach_count": int(bad.sum()),
            "breach_original_win_rate": float((a.original_return > 0).mean()) if len(a) else np.nan,
            "breach_original_mean_return": float(a.original_return.mean()) if len(a) else np.nan,
            "nonbreach_count": int((~bad).sum()),
            "nonbreach_original_win_rate": float((b.original_return > 0).mean()) if len(b) else np.nan,
            "nonbreach_original_mean_return": float(b.original_return.mean()) if len(b) else np.nan,
        })
pd.DataFrame(summ).to_csv(OUT / "threshold_summary.csv", index=False)

print("minute-data gate PASS")
print("signals:", len(feat))
print(grid.sort_values(["mean_return_diag", "win_rate_diag"], ascending=False).head(20).to_string(index=False))
